displayName=Freyja's Flora
author=Paalm
description=Tracks herb, hops, tree, fruit tree, hardwood, calquat, coral, seaweed, and birdhouse runs with visual reminders and routes
tags=farming,herb,hops,tree,fruit,hardwood,calquat,coral,seaweed,birdhouse,hunter,timer,route,path
version=
plugins=com.farmrunhelper.FarmRunHelperPlugin
build=standard
